window.lyrics = [
  [3.771, "robin mehner and his gang of four"],
  [8, "came together at their own front door"],
  [11.3, "there's ola and katharina"],
  [16, "matti and don't forget lena"],

  [19.5, "they didn't get accepted to"],
  [24, "the one and only jsconf.eu"],
  [28, "but berlin is a big city"],
  [31, "with an even bigger community"],

  [35, "we are the rejects"],
  [39, "we are the rejects"],
  [43.5, "this wasn't the conference we want"],
  [47.5, "that's why we sing this song"],

  [51.5, "felix made magic in 3d"],
  [55, "johannes knows a lot about debugging"],
  [59.5, "romain talked about beekeeping"],
  [63, "who doesn't love some p2p?"],

  [67.5, "stefanie located pokémon"],
  [72, "mouse braun punked out to go it alone"],
  [76, "kamil loves the ampersand"],
  [78, "and stephan's plans are mighty grand"],

  [83, "we are the rejects"],
  [87, "we are the rejects"],
  [91.5, "this wasn't the conference we want"],
  [96, "that's why we sing this song"],

  [99.5, "tina's number formatting"],
  [103.5, "and jonathan is machine learning"],
  [107.5, "felix is image processing"],
  [111.5, "and nick is sleepy time hacking"],

  [115.5, "the crazy stuff that is done with js"],
  [120, "and this is only by the rejects"],
  [124, "it's all really kind of ridiculous"],
  [128, "go home, j.s., you're drunk."],

  [131, "we are the rejects"],
  [135, "we are the rejects"],
  [139.5, "this wasn't the conference we want"],
  [143.5, "that's why we sing this song"],

  [155, "j.s. you’re drunk!"],
  [157, "j.s. you’re drunk!"],
  [159, "j.s. you’re drunk!"],
  [161, "j.s. you’re drunk!"],
  [163, "j.s. you’re drunk!"],
  [165, "j.s. you’re drunk!"],
  [167, "j.s. you’re drunk!"],
  [169, "j.s. you’re drunk!"],
  [171, "false isn’t false!"],
  [173, "false isn’t false!"],
  [175, "not a number!"],
  [177, "not a number!"],
  [179, "parsed integers!"],
  [181, "parsed integers!"],
  [183, "j.s. you’re drunk!"],
  [185, "j.s. you’re drunk!"],

  [187, "we are the rejects"],
  [191, "we are the rejects"],
  [195, "we are the rejects"],
  [199, "we are the rejects"],
  [203, "this wasn’t the conference we want"],
  [207, "that’s why we sing this song"]
];